apiVersion: v1
kind: Service
metadata:
  name: redis-dev
spec:
  selector:
    app: redis-dev
  ports:
    - protocol: TCP
      port: 16379         # 서비스가 내부에서 사용하는 포트
      targetPort: 6379   # Pod 내부에서 사용하는 포트
      nodePort: 30007    # NodePort를 명시적으로 설정 (30000 ~ 32767 사이의 값)
  type: NodePort