apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
spec:
  type: NodePort
  selector:
    app: mysql-dev
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006  # (30000-32767 사이의 값)
