apiVersion: v1
kind: Service
metadata:
  name: mysql-dev-service
spec:
  selector:
    app: mysql-dev
  ports:
    - protocol: TCP
      port: 13306        # 서비스가 내부에서 사용하는 포트
      targetPort: 3306  # Pod 내부에서 사용하는 포트
      nodePort: 30008
  type: NodePort