apiVersion: v1
kind: Service
metadata:
  name: redis-dev-service
spec:
  selector:
    app: redis-dev
  ports:
    - protocol: TCP
      port: 6379         # 서비스가 내부에서 사용하는 포트
      targetPort: 6379   # Pod 내부에서 사용하는 포트
      nodePort: 30007
  type: NodePort